### ISSUE TITLE
tag_fallback can deploy unmerged images

### ISSUE THREAD

**Issue by cberg-aot** [bcgov-nr/action-builder-ghcr#45]
![image](https://github.com/bcgov-nr/action-builder-ghcr/assets/93226309/f716f157-66e9-4adb-8f91-d58e2140f65c)

Scenerio: 
- Dev A Opens and Closes PR
- - image gets tagged with latest on pr-close
- Dev B Opens PR with no changes 
- - action-builder detects no changes in service, tries to retag image
- Image with tag_fallback latest gets deployed (unmerged image)

**Comment by DerekRoberts** [comment]
That sounds like a problem with pr-close. We resolved this, right?  Closing, but please to speak up.
